management:
    address: 0.0.0.0
    port: 3001
    security:
        enabled: false

server:
    address: 0.0.0.0
    port: 8000

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
