management:
  security:
    enabled: false

server:
  address: 0.0.0.0
  port: 8761

eureka:
  client:
    register-with-eureka: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
    fetch-registry: false
