management:
  address: 0.0.0.0
  port: 3004
  security:
      enabled: false

server:
  address: 0.0.0.0
  port: 8761

spring:
  boot:
    admin:
      url: http://localhost:8000

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0