management:
  address: 0.0.0.0
  port: 3003
  security:
      enabled: false

server:
  address: 0.0.0.0
  port: 8002

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://localhost:8761}/eureka/