management:
  security:
      enabled: false

server:
  address: 0.0.0.0
  port: 8002

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
