management:
    address: 0.0.0.0
    port: 3002
    security:
        enabled: false

server:
    address: 0.0.0.0
    port: 8001

spring:
  boot:
    admin:
      url: http://localhost:8000
  cloud:
    config:
      server:
        git:
          uri: http://zgbwcdevconfig01.jupiter.bbc.co.uk/Jonathan/eng-bsd-configuration.git
